### ISSUE TITLE
Mean of empty slice warning in PCI reconstructor

### ISSUE THREAD

**Issue by sdmccabe** [netsiphd/netrd#127]
```{python}
tests/test_reconstruction.py::test_graph_size
  /home/main/git/netrd/netrd/reconstruction/partial_correlation_influence.py:93: RuntimeWarning: Mean of empty slice
    p_cor_inf = np.nanmean(p_cor_zs, axis=2) # mean over the Y axis
```
Not sure anything's wrong per se, but this warning could use some investigating.

**Comment by sdmccabe** [comment]
Still haven't gotten to the bottom of this entirely, but two things worth noting.

1. On a toy example, I was getting a different warning - `invalid value encountered in double_scalars` - that seemed to be because of the `nan`s in the diagonal. Removing the `np.fill_diagonal()` call got rid of that error, I think without changing the final output. I'm not sure what the interpretation of the `nan`s are here so I'm hesitant to change it until I know why it's there.
2. Our partial correlation function (which is mostly copied from a gist) has somewhat odd behavior. My intuition for partial correlation is that the least-squares equations used for generating the residuals should include an intercept term. The R-based example used on the [Wikipedia page](https://en.wikipedia.org/wiki/Partial_correlation) also includes an intercept. However, `scipy.linalg.lstsq` does *not* include an intercept term. This leads to different partial correlation values; since we're really interested in the relative partial correlations of each (i, j) this is probably not a huge deal, but something to note.

**Comment by chiahungyang** [comment]
My guess is that partial correlation fails to identify self-loop interactions, and I suspect this is what caused the warnings.

Let `\rho(X,Y:Z)` be the partial correlation between variable X and Y given Z. It is defined as the Pearson correlation coefficient between `e(X~Z)` and `e(Y~Z)`, where `e(X~Z)` stands for the residuals of X regressed on Z. In order to find causal relation between variables, the current implementation involves caculating `\rho(X:Z)` which is the average of `\rho(X,Y:Z)` for all Y different from X and Z. This produces the partial correlation matrix, and it is used to infer existence of link `Z -> X` after thresholding (for partial correlation influence there is one additional step before computing the average but subtle in this issue).
However, if `Z = X`, then hypothetically `e(X~Z)` is a zero vector. The Pearson correlation coefficient between `e(X~Z)` and any `e(Y~Z)`, hence the partial correlation `\rho(X,Y:Z)` for any Y and surely `\rho(X:Z)`, is ill-defined. The above discusstion **shows that partial correlation is not capable to infer self-loops** due to such ambiguity.

In the current implementation `partial_correlation_influence.py` where we are using `scipy.stats.pearsonr`, it returns `nan` when one of its input has zero standard deviation. Thus in array `p_cor_zs` had entry `nan` wherever `Z = X` (the diagonal plane for the first two axes). And `np.nanmean(p_cor_zs, axis=2)` complained about taking non-nan mean on an 1D array full of `nan`.

I see two plausible solutions here. For one we can discuss how to deal with Pearson correlation coefficient when one variable has zero standard deviation. For the other we can force the reconstructor to always exclude self-loops. The latter can be done by setting `\rho(X:Z) = -np.inf` for every `Z = X`, and the thresholding will never return these self-loops.

**Comment by sdmccabe** [comment]
This is really good stuff. I think this is likely the issue (though we should revisit the intercept issue I raised at some point). My instinct is to try and trim the self-loops in the way you suggest and see if that improves the performance, but it might make sense to check the papers again before making that change.

**Comment by chiahungyang** [comment]
So I went back to [the paper of partial correlation influence](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0015032). They constructed the network in a quite different way from our thresholding method, where they used the partial correlation influence matrix to build a [planar graph](https://en.wikipedia.org/wiki/Planar_graph). I believe this belongs to the class of simple graphs so no self-loops were involved. Since we've adopted a different thresholding procedure, I would say it's safe to exlude self-loops in this reconstructor.

**Comment by chiahungyang** [comment]
Meanwhile for the intercept issue @sdmccabe you brought up, and digging into [this paper which defined partial correlation](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1467-842X.2004.00360.x), it described residuals as **the deviation of _X_ from its projection on the linear space spanned by _Z_**. This makes me leaning toward **NOT** to include the intercept term. Including an intercept term creates an artificial variable whose time series is an one-vector, which doesn't seem to match the description in the paper.
