### ISSUE TITLE
Distance => metrics?

### ISSUE THREAD

**Issue by gstonge** [netsiphd/netrd#139]
Just a thought : should we enforce that all the distance measures are "metrics" in the strict term? For instance, many measures, portrait_divergence for instance, return directly the Jensen-Shannon divergence, while others return the square root of the JSD. The latter is a metric, JSD directly is not, as far as I know. This could apply also to other distance measures, not just the ones related to the JSD.

**Comment by sdmccabe** [comment]
Do we have a sense of how many of them are metrics? I think @leotrs's method wouldn't qualify (it's a pseudometric, if I remember his paper correctly), and @tlarock pointed out that the DeltaCon paper talks about how hard it is for a graph distance to be a metric. (Whichever ones **are** metrics, we should document.)

Since part of the goal was to evaluate the distance measures, I would be hesitant to deviate from the canonical implementations too much. Making portrait divergence return the square root wouldn't be a big deal, but other methods might require more changes.

The DeltaCon paper suggests three conditions for a graph similarity. @leotrs's paper restates them in terms of graph distances:

1. the distance of a graph from itself is 0
2. the distance is symmetric (see #136)
3. the distance between the complete graph and the empty graph of size N approaches infinity as N goes to infinity

I think for the last one, since we have some that are bound on [0, 1], we could just say that the distance between between the complete graph and the empty graph does not decrease with size.

**Comment by sdmccabe** [comment]
FWIW, I tried writing a test for the third of those conditions and a lot of the methods struggle to handle empty graphs, so even the DeltaCon conditions might be too stringent.

**Comment by leotrs** [comment]
Enforcing metricity would disqualify a lot of distances. In particular, it would disqualify every distance that depends on eigenvalues/eigendecomposition due to cospectrality (there exist non-isomorphic graphs with the same eigenvalues). Moreover, even if we wanted to enforce it, I don't know how we would test for it. I agree possibly the best path is to just label every distance with whether or not they are metrics, pseudo-metrics or neither.

RE DeltaCon properties: yes, a lot of the measures are not even defined for empty graphs. We can relax that requirement by saying that the distance between the complete graph and a dyad grows larger the more nodes the complete graph says. Or we could replace a dyad with a cycle? tree? set of dyads? if we wanted to only compare graphs of the same size.

If we are going to label measures by metricity, we might as well indicate when they are (not) defined. We could label each distance with whether it is defined on not connected graphs, or multigraphs, or only for graphs of the same size, etc.

PS [Link to my paper](http://leotrs.com/static/graph-distance-topological.pdf). See bottom half of page 7 for relevant properties.

**Comment by leotrs** [comment]
I propose we document somewhere the fact that most of the methods we have are not metrics and close this. Where in the documentation should we put this?

**Comment by hartle** [comment]
Maybe in the official big table of methods we could have a column that has "metric", "pseudometric", or "nonmetric" for each distance measure?

**Comment by sdmccabe** [comment]
I think it's cleanest to do this in a table rather than in individual docs (especially if we're committed to the two-step process discussed in #174). This could go in the README initially, but would likely make most sense to address after we set up a readthedocs (#177).
