### ISSUE TITLE
Adding Licensed Code

### ISSUE THREAD

**Issue by gitronald** [netsiphd/netrd#30]
Some of the measures we want to implement are already implemented under permissive licenses. For example, Ipsen-Mikhailov distance (and several others) are implemented [here](https://github.com/makism/dyfunconn/tree/master/dyfunconn/graphs). How do we want to include these licenses in `netrd`?

**Comment by leotrs** [comment]
Are you planning on rewriting the code from that repo? Or on importing the code from it directly and just wrap around it?

If all we are doing is rewriting, I think we are in the clear. The repository you linked to has [this](https://github.com/makism/dyfunconn/blob/master/LICENSE) license, so we are in the clear because (i) we are not using that software, we are writing our own based on that, and (ii) their license is actually very permissive.

If there are other cases where we want to *use* software with a more restrictive license, we would have to think about that on a case-by-case basis (unless anyone thinks of anything better?)

**Comment by sdmccabe** [comment]
Flag licenses that aren't OSI approved, maybe?

**Comment by sdmccabe** [comment]
We should do this before NetSci.

**Comment by sdmccabe** [comment]
So we think most all of the code here is rewritten, and what is adapted from other implementations are under the same (MIT) license as netrd. After adding language about licenses to `CONTRIBUTING` (#168), I think we'll be good to go here.
