### ISSUE TITLE
Graph Embeddings and Distances

### ISSUE THREAD

**Issue by tlarock** [netsiphd/netrd#33]
This issue is meant to be addressed in the future (meaning after this first weekend of work), but it has already been raised so I wanted to pin it for open discussion here.

One way to compute a distance between graphs is to embed both graphs in a lower dimensional space, then compute a distance between the embeddings. More similar graphs should have "similar" embeddings. However, including this technique in our paper/repository opens a ginormous can of worms, because there are approximately 1 trillion different graph embeddings (go to page 22 of the [KDD 2018 conference program](https://www.kdd.org/kdd2018/files/KDD2018BookletShared.pdf) and ctrl+f for "embedding". I counted over 10 network papers before I gave up. This happens at multiple conferences per year over the last 5+ years). There are also many ways to compute similarity measures on matrices, and the "best" way almost certainly depends on the particular embedding algorithm. So in my view including embeddings is basically like adding another layer to this project (Collabathon 2020: Embeddings Strike Back??).

**Comment by leotrs** [comment]
1. What exactly would be the topic of 2020? There already are a number of surveys [[1](https://arxiv.org/pdf/1705.02801.pdf), [2](https://arxiv.org/pdf/1709.07604.pdf)] on graph embeddings, as well as [repositories](https://github.com/palash1992/GEM) that implement a bunch of them.

2. See Table 1 in [1], I think most of the ones under "Factorization" would be deterministic. I don't recall off the top of my head if they instruct the reader on how to use them for comparison. I'd be surprised if anyone did this since graph distance/comparison is not really the point of embedding.

**Comment by sdmccabe** [comment]
I think we've decided to not do embeddings.
