### ISSUE TITLE
Input Validation of Methods

### ISSUE THREAD

**Issue by ryanjgallagher** [netsiphd/netrd#37]
Should we validate input into graph distance / reconstruction algorithms? For example, the algorithm we're working on right now expects graphs of the same size and will end up throwing an error eventually if they have a different number of nodes. Should we check this ahead of time? If so, should we return an empty graph if there's invalid input, or should we throw an error? What kind of error?

**Comment by tlarock** [comment]
Since we are not systematically validating input, my recommendation would be to use an [assertion](https://www.tutorialspoint.com/python/assertions_in_python.htm) here to ensure that the method doesn't try to run with invalid input. This also takes care of the return problem, since an assertion will end execution and nothing needs to be returned. This will serve as a temporary solution until we develop more robust data validation and error handling conventions. Others please sound off with differing opinions.

**Comment by sdmccabe** [comment]
I think assertions are sensible in that case. In general, I would only worrying about validating things specific to an algorithm; i.e., we shouldn't deal with testing whether or not a distance measure is receiving two networkx Graphs.

**Comment by tlarock** [comment]
Fine with raising `ValueError` instead of using an assertion. Suggest we add to the `template.py` comments as @leotrs suggested and close this issue.
