### ISSUE TITLE
for random reconstruction method

### ISSUE THREAD

**Issue by jkbren** [netsiphd/netrd#66]
it currently returns an ER network, what if we return a random NxN matrix and parameterize the method to have a threshold, something like

tau=0.8
W = np.random.rand(N,N)
A = np.array(W > tau, dtype=int)
G = nx.from_numpy_array(A)

**Comment by Carromattsson** [comment]
I'm not sure how to use something like this. It's not a null model for anything in particular.

I would suggest instead we provide several random time series with different properties (and different pre-processing!) so that anyone can test their reconstruction method on something that isn't supposed to have any structure to it.

**Comment by leotrs** [comment]
The random reconstructor was meant to be just a placeholder/example from before we even started committing methods. Now that we have a bunch of them, I think we can safely delete it and add something more systematic like what @Carromattsson is suggesting.

**Comment by Carromattsson** [comment]
Ah, I see, in that context it makes perfect sense - carry on 😅

The random time series thing is more for systematic comparison of methods under different conditions. I think Harrison has been thinking along those lines for a while. I bet he has ideas beyond a random “null”, also.

**Comment by sdmccabe** [comment]
I think this was resolved by #75.
