### ISSUE TITLE
Pre-processing can change the interpretation of a method

### ISSUE THREAD

**Issue by Carromattsson** [netsiphd/netrd#68]
Following this lunch's conversation, I took a look at how financial time series are built. The consensus across all the papers I've been pulling from is: 

Y_i = ln[P_i(t)] − ln[P_i(t − 1)] where Pi(t) is the closure price of the stock i at the day t.

Setting aside the logging, this is rather tricky because I don't think differencing is universal. The interpretation of a correlation matrix of this time series is different from it's interpretation when built from raw values, as Brennan noted. I imagine that time series in neuroscience are not built the same way? 

This issue is transparently clear for something as easy/dumb as a correlation matrix, but the main concern applies across methods and it may be much harder to see. Is a given method expecting a raw series of counts/intensity, one that is normalized in some way, or one that quantifies change? What does it do if it's given something different? Does it still make sense?

One way to navigate this is to enforce that every method we're implementing takes raw or scaled time series. I would then write a second correlation matrix reconstruction method that includes the differencing/derivative as a part of it, and name it something distinct.  

Another way is to make very very clear for each method what kind of input it is expecting, or if it works for multiple, how the interpretation of it changes and who uses it how. 

Sigh. Complicated :(

**Comment by leotrs** [comment]
This is a good point, but I think it's better addressed from a documentation/writeup point of view than from a coding point of view. If the main difference between the current corr. matrix method and the one you propose is one pre-processing step, then I'd prefer not implementing it and making the difference clear in the documentation. 

From a library design point of view, I'd rather implement just the on method and let the user decide how they're going to use it.

From an experimental point of view, however, it might be nice to have all of the methods take exactly the same type of time series ("raw", instead one that quantifies change). I'm going to let @tlarock @jkbren chip in on that since they are thinking about the experimental pipeline.

In any case, this is definitely something we should dedicate a paragraph to in the end paper.

**Comment by Carromattsson** [comment]
Thanks @leotrs, I agree with you 100%
